name: FAQ ROBOT
server:
  port: 80

mybatis:
  config-location:  classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.vitco.sr.entity

spring:
  # profiles:
  # active: dev
  datasource:
    # url: jdbc:mysql://127.0.0.1:3306/test_yl?useUnicode=true&characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://192.168.13.233:3306/test_yl?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: test_yl
    password: test_1234
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

lucene:
  indexPath: ../lidx/data
  # noload    reload 两种模式
  runMode: reload