name: FAQ ROBOT
server:
  port: 8080

mybatis:
  config-location:  classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.vitco.sr.entity

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test_yl?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: test_yl
    password: 212223
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource