name: FAQ ROBOT
server:
  port: 80
mybatis:
  config-location:  classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml


datasource:
  url: jdbc:mysql://192.168.13.233:3306/test_yl
  username: test_yl
  password: test_1234
  driver-class-name: com.mysql.jdbc.Driver
  # 使用druid数据源
  type: com.alibaba.druid.pool.DruidDataSource

